version: "3"

services:
  ui:
    build: ui
    ports:
      - "80:80"
    container_name: ui-container
  server:
    build: server
    ports:
      - "3000:3000"
    container_name: server-container
    restart: always
    depends_on:
      - database
  database:
    image: mongo:3.6.19-xenial
    container_name: database-container
    restart: always
    ports:
      - "27017:27017"
    networks:
    - mean-app
    volumes:
      - mongo-data:/data/db

networks:
  mean-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local