version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3
  slack: circleci/slack@4.1.2

jobs:
  server_lint_test_build:
    working_directory: ~/digicard
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-server-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-server-dependencies-
      - run:
          name: server npm install
          command: npm install;
      - save_cache:
          key: v1-server-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: server lint
          command: cd ./server; xvfb-run -a npm run lint
      - run:
          name: server test
          command: cd ./server; xvfb-run -a npm run test
      - run:
          name: server build
          command: cd ./server;

  ui_lint_test_build:
    working_directory: ~/digicard
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ui-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-ui-dependencies-
      - run:
          name: ui npm install
          command: cd ./ui && npm install;
      - save_cache:
          key: v1-ui-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./ui/node_modules
      - run:
          name: ui lint
          command: cd ./ui; xvfb-run -a npm run lint
      - run:
          name: ui test
          command: cd ./ui; xvfb-run -a npm run test -- --watch=false --progress=false --browsers=ChromeNoSandbox
      - run:
          name: ui build
          command: cd ./ui; xvfb-run -a npm run build

  deploy_heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - slack/notify:
          channel: circleci
          event: fail
          template: basic_fail_1
          mentions: "@andresceron"
      - slack/notify:
          channel: circleci
          event: pass
          template: success_tagged_deploy_1

workflows:
  default:
    jobs:
      - server_lint_test_build # your custom job from your config, that builds your code
      - ui_lint_test_build: # your custom job; runs test suite 1
          requires: # test1 will not run until the `build` job is completed.
            - server_lint_test_build
      - deploy_heroku: # another custom job; runs test suite 2,
          requires: # test2 is dependent on the success of job `test1`
            - server_lint_test_build
            - ui_lint_test_build
          context: slack-secrets
          filters:
            branches:
              only:
                - main
                - /DIG-.*/
