version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3
  slack: circleci/slack@4.2.0

jobs:
  server_lint_test_build:
    working_directory: ~/digicard
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-server-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-server-dependencies-
      - run:
          name: server npm install
          command: npm install;
      - save_cache:
          key: v1-server-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: server lint
          command: cd ./server; xvfb-run -a npm run lint
      - run:
          name: server test
          command: cd ./server; xvfb-run -a npm run test
      - run:
          name: server build
          command: cd ./server;
      - slack/notify:
          channel: circleci
          event: fail
          custom: |
            {
                "blocks": [
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": "SOCIALAR - FAILED :red_circle: (${CIRCLE_JOB_NUM})",
                            "emoji": true
                        }
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Project*: $CIRCLE_PROJECT_REPONAME \\n"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Branch*: $CIRCLE_BRANCH \\n"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Author*: $CIRCLE_USERNAME \\n"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Mentions*: $SLACK_PARAM_MENTIONS \\n"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Job*: ${CIRCLE_JOB} \\n"
                            }
                        ]
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View Job"
                                },
                                "url": ${CIRCLE_BUILD_URL}
                            }
                        ]
                    }
                ]
            }

  ui_lint_test_build:
    working_directory: ~/digicard
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ui-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-ui-dependencies-
      - run:
          name: ui npm install
          command: cd ./ui && npm install;
      - save_cache:
          key: v1-ui-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./ui/node_modules
      - run:
          name: ui lint
          command: cd ./ui; xvfb-run -a npm run lint
      - run:
          name: ui test
          command: cd ./ui; xvfb-run -a npm run test -- --watch=false --progress=false --browsers=ChromeNoSandbox
      - run:
          name: ui build
          command: cd ./ui; xvfb-run -a npm run build
      - slack/notify:
          channel: circleci
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "SOCIALAR: FAILED :red_circle:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Mentions*: $SLACK_PARAM_MENTIONS \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB} \\n"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": ${CIRCLE_BUILD_URL}
                    }
                  ]
                }
              ]
            }

  deploy_heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - slack/notify:
          channel: circleci
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "SOCIALAR: FAILED :red_circle:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Mentions*: $SLACK_PARAM_MENTIONS \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB} \\n"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": ${CIRCLE_BUILD_URL}
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          channel: circleci
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "SOCIALAR: SUCCESSFUL :red_circle:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Mentions*: $SLACK_PARAM_MENTIONS \\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB} \\n"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": ${CIRCLE_BUILD_URL}
                    }
                  ]
                }
              ]
            }

workflows:
  default:
    jobs:
      - server_lint_test_build # your custom job from your config, that builds your code
      - ui_lint_test_build: # your custom job; runs test suite 1
          requires: # test1 will not run until the `build` job is completed.
            - server_lint_test_build
          context: slack-secrets
      - deploy_heroku: # another custom job; runs test suite 2,
          requires: # test2 is dependent on the success of job `test1`
            - server_lint_test_build
            - ui_lint_test_build
          context: slack-secrets
          filters:
            branches:
              only:
                - main
                - /DIG-.*/
