version: 2.1
jobs:
  build:
    working_directory: ~/digicard
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "./ui/package.json" }}
            - v1-dependencies-
      - run: cd ./ui; npm install
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "./ui/package.json" }}
          paths:
            - ./ui/node_modules
      - run:
          name: ng lint
          command: cd ./ui; xvfb-run -a npm run lint
      - run:
          name: ng test
          command: cd ./ui; xvfb-run -a npm run test -- --watch=false --progress=false --browsers=ChromeNoSandbox
      # - run:
      #     name: ng e2e
      #     command: cd ./ui; xvfb-run -a npm run e2e -- --protractorConfig=e2e/protractor-ci.conf.js

# workflows:
#   build:
#     jobs:
#       - bar:
#           pre-steps: # steps to run before steps defined in the job bar
#             - run:
#                 command: cd ./ui
