name: Socialar Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy-server:
    name: Build and deploy SERVER
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v1
       with:
         dockerfile: server/Dockerfile
         repository: andresceron/socialar-server
         tags: latest
         # file: ./server/Dockerfile

#  build-deploy-ui:
#    name: Build and deploy UI
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - 
#       name: Setup Docker Buildx
#       uses: docker/setup-buildx-action@v1
#      -
#       name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#       name: Build and push
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./ui/Dockerfile
#         push: true
#         tags: socialar-ui:latest    
