name: Socialar Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy-server:
    name: Build and deploy SERVER
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: .
         file: server/Dockerfile
         tags: andresceron/socialar-server:latest
         push: true

  build-deploy-ui:
    name: Build and deploy UI
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ui/Dockerfile
          tags: andresceron/socialar-ui:latest
          push: true
